In [3]:
import os
print(os.getcwd())

import warnings
warnings.filterwarnings(action='ignore')

c:\jupyter_home\통합프로젝트\library\code

In [4]:
import pandas as pd

In [3]:
df = pd.read_csv('../data2/library_learning_dataset.csv')
df.info()
display(df.head())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 80000 entries, 0 to 79999
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   user_key      80000 non-null  object
 1   loan_date     80000 non-null  object
 2   return_date   80000 non-null  object
 3   isbn13        80000 non-null  int64
 4   title         80000 non-null  object
 5   author        80000 non-null  object
 6   publisher     80000 non-null  object
 7   add_code      80000 non-null  float64
 8   img_url       80000 non-null  object
 9   kdc_class_no  80000 non-null  float64
 10  sex           80000 non-null  float64
 11  age           80000 non-null  float64
dtypes: float64(4), int64(1), object(7)
memory usage: 7.3+ MB

,user_key,loan_date,return_date,isbn13,title,author,publisher,add_code,img_url,kdc_class_no,sex,age
0,D42A0AECF86DE543E159EBCF1F440F55BD9CEF5F,2022-03-31 12:00:00.0,2022-04-18 12:00:00.0,9788932105635,주님의 기도:해설,로마노 구아르디니 저;이석은 역,가톨릭출판사,3230.0,http://image.aladin.co.kr/product/29/95/cover/...,233.6900,0.0,0.0
1,C0149AC77AF2058BCA3E07FE765A0E30837261EA,2022-04-19 12:00:00.0,2022-04-21 12:00:00.0,9788977990371,建築技術,용갑식;최상민 [공]지음,공간예술사,93560.0,http://image.aladin.co.kr/product/25/26/cover/...,542.8000,0.0,0.0
2,D42A0AECF86DE543E159EBCF1F440F55BD9CEF5F,2022-03-31 12:00:00.0,2022-04-18 12:00:00.0,9788932105567,생명의 옹달샘,[가톨릭출판사]편집부 엮음,가톨릭출판사,4230.0,https://bookthumb-phinf.pstatic.net/cover/014/...,234.2000,0.0,0.0
3,E1A7C4AF8B9356CE5A15199E17707545DD7D76DB,2022-04-19 12:00:00.0,2022-04-22 12:00:00.0,9788931418828,전자상거래관리사 2급 필기 마스터바이블:전자상거래관련법규,배근성;영진정보연구소 공저,영진닷컴,13000.0,http://image.aladin.co.kr/product/30/30/cover/...,326.1650,0.0,0.0
4,D42A0AECF86DE543E159EBCF1F440F55BD9CEF5F,2022-03-31 12:00:00.0,2022-04-18 12:00:00.0,9788988800980,이민 가서 뭐해 먹고 살지:뉴질랜드 편,진양경 씀,무한,3810.0,http://image.aladin.co.kr/product/30/25/cover/...,322.9563,0.0,0.0

In [6]:
df[['kdc_class_no','age','sex']] = df[['kdc_class_no','age','sex']].astype(int)

In [11]:
display(df.head())

,user_key,loan_date,return_date,isbn13,title,author,publisher,add_code,img_url,kdc_class_no,sex,age
0,D42A0AECF86DE543E159EBCF1F440F55BD9CEF5F,2022-03-31 12:00:00.0,2022-04-18 12:00:00.0,9788932105635,주님의 기도:해설,로마노 구아르디니 저;이석은 역,가톨릭출판사,3230.0,http://image.aladin.co.kr/product/29/95/cover/...,233,0,0
1,C0149AC77AF2058BCA3E07FE765A0E30837261EA,2022-04-19 12:00:00.0,2022-04-21 12:00:00.0,9788977990371,建築技術,용갑식;최상민 [공]지음,공간예술사,93560.0,http://image.aladin.co.kr/product/25/26/cover/...,542,0,0
2,D42A0AECF86DE543E159EBCF1F440F55BD9CEF5F,2022-03-31 12:00:00.0,2022-04-18 12:00:00.0,9788932105567,생명의 옹달샘,[가톨릭출판사]편집부 엮음,가톨릭출판사,4230.0,https://bookthumb-phinf.pstatic.net/cover/014/...,234,0,0
3,E1A7C4AF8B9356CE5A15199E17707545DD7D76DB,2022-04-19 12:00:00.0,2022-04-22 12:00:00.0,9788931418828,전자상거래관리사 2급 필기 마스터바이블:전자상거래관련법규,배근성;영진정보연구소 공저,영진닷컴,13000.0,http://image.aladin.co.kr/product/30/30/cover/...,326,0,0
4,D42A0AECF86DE543E159EBCF1F440F55BD9CEF5F,2022-03-31 12:00:00.0,2022-04-18 12:00:00.0,9788988800980,이민 가서 뭐해 먹고 살지:뉴질랜드 편,진양경 씀,무한,3810.0,http://image.aladin.co.kr/product/30/25/cover/...,322,0,0

In [73]:
loan = df['user_key'].value_counts()

In [74]:
loan

5c2ea6f6-2cd4-00f4-e053-0a0a3202a227                                75
B8C4975428B4F82F66D5E08BF7CF57145F00D688                            65
1A238557FB307E1734A1F6249436E1E6D629449A                            60
6aa210d34c2a70bdd90b0593d0be98d193f003d87a99fe83e31ce0a7b8e93826    59
0F556CA6B6D15595D949563F83689DEB65C92295                            59
                                                                    ..
89D5FC0F6C5B34B589D9FBF832F8C279688D8288                             1
5c2ea6f2-49b9-00f4-e053-0a0a3202a227                                 1
5c2ea6f4-f94c-00f4-e053-0a0a3202a227                                 1
B9630823F683CD61B5FF1DCFE4091151866B996C                             1
5c2ea6f3-c721-00f4-e053-0a0a3202a227                                 1
Name: user_key, Length: 17163, dtype: int64

In [75]:
loan = loan.to_frame(name='T')
loan.reset_index(drop=False, inplace=True)
display(loan)

                                                   index   T
0                   5c2ea6f6-2cd4-00f4-e053-0a0a3202a227  75
1               B8C4975428B4F82F66D5E08BF7CF57145F00D688  65
2               1A238557FB307E1734A1F6249436E1E6D629449A  60
3      6aa210d34c2a70bdd90b0593d0be98d193f003d87a99fe...  59
4               0F556CA6B6D15595D949563F83689DEB65C92295  59
...                                                  ...  ..
17158           89D5FC0F6C5B34B589D9FBF832F8C279688D8288   1
17159               5c2ea6f2-49b9-00f4-e053-0a0a3202a227   1
17160               5c2ea6f4-f94c-00f4-e053-0a0a3202a227   1
17161           B9630823F683CD61B5FF1DCFE4091151866B996C   1
17162               5c2ea6f3-c721-00f4-e053-0a0a3202a227   1

[17163 rows x 2 columns]

In [77]:
loan.rename(columns = {'index':'user_key'}, inplace=True)
display(loan)

                                                user_key   T
0                   5c2ea6f6-2cd4-00f4-e053-0a0a3202a227  75
1               B8C4975428B4F82F66D5E08BF7CF57145F00D688  65
2               1A238557FB307E1734A1F6249436E1E6D629449A  60
3      6aa210d34c2a70bdd90b0593d0be98d193f003d87a99fe...  59
4               0F556CA6B6D15595D949563F83689DEB65C92295  59
...                                                  ...  ..
17158           89D5FC0F6C5B34B589D9FBF832F8C279688D8288   1
17159               5c2ea6f2-49b9-00f4-e053-0a0a3202a227   1
17160               5c2ea6f4-f94c-00f4-e053-0a0a3202a227   1
17161           B9630823F683CD61B5FF1DCFE4091151866B996C   1
17162               5c2ea6f3-c721-00f4-e053-0a0a3202a227   1

[17163 rows x 2 columns]

In [82]:
loan_5 = loan[loan['T'] > 5]

In [83]:
df_5 = pd.merge(df, loan_5, on=['user_key'], how='inner')
display(df_5)

,user_key,loan_date,return_date,isbn13,title,author,publisher,add_code,img_url,kdc_class_no,sex,age,T
0,D42A0AECF86DE543E159EBCF1F440F55BD9CEF5F,2022-03-31 12:00:00.0,2022-04-18 12:00:00.0,9788932105635,주님의 기도:해설,로마노 구아르디니 저;이석은 역,가톨릭출판사,3230.0,http://image.aladin.co.kr/product/29/95/cover/...,233,0,0,8
1,D42A0AECF86DE543E159EBCF1F440F55BD9CEF5F,2022-03-31 12:00:00.0,2022-04-18 12:00:00.0,9788932105567,생명의 옹달샘,[가톨릭출판사]편집부 엮음,가톨릭출판사,4230.0,https://bookthumb-phinf.pstatic.net/cover/014/...,234,0,0,8
2,D42A0AECF86DE543E159EBCF1F440F55BD9CEF5F,2022-03-31 12:00:00.0,2022-04-18 12:00:00.0,9788988800980,이민 가서 뭐해 먹고 살지:뉴질랜드 편,진양경 씀,무한,3810.0,http://image.aladin.co.kr/product/30/25/cover/...,322,0,0,8
3,D42A0AECF86DE543E159EBCF1F440F55BD9CEF5F,2022-03-31 12:00:00.0,2022-04-18 12:00:00.0,9788972420187,商標法,이수웅;홍봉규 共著,삼선,93320.0,http://image.aladin.co.kr/product/28/41/cover/...,502,0,0,8
4,D42A0AECF86DE543E159EBCF1F440F55BD9CEF5F,2022-03-17 12:00:00.0,2022-03-31 12:00:00.0,9788959639014,와일드 라이프=Wild life,Fujisaki Masato 저,코암나노바이오 대원씨아이,7650.0,https://image.aladin.co.kr/product/65/4/cover/...,830,0,0,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...
50125,903BDFCBDD4CBC5D91DAC0C9F6F3EB76F82D3C3F,2022-03-26 12:00:00.0,2022-04-13 12:00:00.0,9791190153829,1초,글: 시니 ;그림: 광운,영컴,7810.0,https://image.aladin.co.kr/product/27321/36/co...,810,1,3,10
50126,903BDFCBDD4CBC5D91DAC0C9F6F3EB76F82D3C3F,2022-03-26 12:00:00.0,2022-04-13 12:00:00.0,9791190153812,1초,글: 시니 ;그림: 광운,영컴,7810.0,https://image.aladin.co.kr/product/27321/32/co...,810,1,3,10
50127,903BDFCBDD4CBC5D91DAC0C9F6F3EB76F82D3C3F,2022-03-26 12:00:00.0,2022-04-13 12:00:00.0,9791167042903,(OK) 9급 기출문제집 :2021~2017,박문각출판문화연구소 편저,박문각(박문각출판),13350.0,https://image.aladin.co.kr/product/28034/7/cov...,351,1,3,10
50128,903BDFCBDD4CBC5D91DAC0C9F6F3EB76F82D3C3F,2022-03-26 12:00:00.0,2022-04-13 12:00:00.0,9788936322205,소비자학의 기초 =Introduction to consumer science,허경옥 지음,교문사,93590.0,https://image.aladin.co.kr/product/27813/85/co...,321,1,3,10
50129,903BDFCBDD4CBC5D91DAC0C9F6F3EB76F82D3C3F,2022-03-26 12:00:00.0,2022-04-13 12:00:00.0,9791167041852,김재준 단권화 행정학 :2022 9·7급 공무원,김재준 편저,박문각(박문각출판),14350.0,https://image.aladin.co.kr/product/27878/38/co...,351,1,3,10

In [85]:
df_5.to_csv('../data2/library_learning_dataset_loan5.csv', index = False)