In [6]:
import os
print(os.getcwd())

import warnings
warnings.filterwarnings(action='ignore')

c:\jupyter_home\통합프로젝트\book_list\code

In [7]:
import pandas as pd

In [5]:
os.listdir('../data')

['book_list', 'user_info']

In [5]:
forders = os.listdir('../data')

In [6]:
cd ../data

c:\jupyter_home\통합프로젝트\book_list\data

In [7]:
import os

path = '../data/'
file_list = os.listdir(path)
file_list_py = [file for file in file_list if file.endswith('.csv')]

df = pd.DataFrame()
for i in file_list_py:
    data = pd.read_csv(path + i, error_bad_lines=False)
    df = pd.concat([df,data])
    
df = df.reset_index(drop = True)

b'Skipping line 783401: expected 11 fields, saw 16\n'
b'Skipping line 2002736: expected 11 fields, saw 16\n'

In [8]:
display(df)

,?master_seq,isbn13,vol,title,author,publisher,pub_date,add_code,price,img_url,description,master_seq,kdc_class_no,title_replace,author_replace,pub_date_2,is_coll_aladin,is_coll_naver,isbn_origin
0,5126174.0,9781402045042,ebk,(The)ecology of transportation:managing mobili...,"edited by John Davenport,Julia L. Davenport",Springer,c2006,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,5126175.0,9780415332798,pbk,Ecosystems,"Gordon Dickinson,Kevin Murphy",Routledge,c2007,NaN,NaN,https://image.aladin.co.kr/product/149/84/cove...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,5126176.0,9780203401378,ebk,Ecosystems,"Gordon Dickinson,Kevin Murphy",Routledge,c2007,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,5126177.0,9781597450126,eisbn,Epidermal growth factor:methods and protocols,"edited by Tarun B. Patel,Paul J. Bertics",Humana Press,c2006,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5126178.0,9780878931897,hbk,Evolutionary biology,Douglas J. Futuyma,Sinauer Associates,c1998,NaN,NaN,https://image.aladin.co.kr/product/118/4/cover...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7597268,NaN,9781191496148,NaN,설민석의 세계사 대모험 11 (영국 산업 혁명 편: 혁명에 맞선 자들),김정욱|설민석,단꿈아이,NaN,NaN,NaN,NaN,NaN,6372497.0,NaN,설민석의세계사대모험11영국산업혁명편혁명에맞선자들,김정욱설민석,NaN,Y,Y,NaN
7597269,NaN,9781161755015,NaN,A Clinical Atlas: Variations of the Bones of t...,Thomas Dwight (지은이),Kessinger Publishing,NaN,NaN,NaN,https://image.aladin.co.kr/product/7275/80/cov...,NaN,6372498.0,NaN,aclinicalatlasvariationsofthebonesofthehandsan...,thomasdwight지은이,2010-05-23,Y,Y,NaN
7597270,NaN,9781197192907,NaN,"과탑이 알려 주는 대학 생활 한 권으로 끝내기 (어서와, 대학은 처음이지?)",조유림,든든한서재,NaN,NaN,NaN,NaN,NaN,6372499.0,NaN,"과탑이알려주는대학생활한권으로끝내기어서와,대학은처음이지",조유림,NaN,Y,Y,NaN
7597271,NaN,9781188005384,NaN,중학영문법 총정리 한권으로 끝내기 (EBS강사 혼공쌤 허준석의 &quot;쉽고 재미...,허준석|정다운,쏠티북스,NaN,NaN,NaN,NaN,NaN,6372500.0,NaN,중학영문법총정리한권으로끝내기ebs강사혼공쌤허준석의quot쉽고재미있게끝내는중학영문법quot,허준석정다운,NaN,Y,Y,NaN
7597272,NaN,9781191334426,NaN,"더 빅 윈 (이룰 것인가, 남길 것인가)",신문범,클라우드나인,NaN,NaN,NaN,NaN,NaN,6372501.0,NaN,"더빅윈이룰것인가,남길것인가",신문범,NaN,Y,Y,NaN

In [9]:
df.columns

Index(['?master_seq', 'isbn13', 'vol', 'title', 'author', 'publisher',
       'pub_date', 'add_code', 'price', 'img_url', 'description', 'master_seq',
       'kdc_class_no', 'title_replace', 'author_replace', 'pub_date_2',
       'is_coll_aladin', 'is_coll_naver', 'isbn_origin'],
      dtype='object')

In [10]:
df = df[df['add_code'].notna()]

In [11]:
df

,?master_seq,isbn13,vol,title,author,publisher,pub_date,add_code,price,img_url,description,master_seq,kdc_class_no,title_replace,author_replace,pub_date_2,is_coll_aladin,is_coll_naver,isbn_origin
23,5126197.0,9788958945116,1,폭마전기 :정재은 新무협 장편소설,정재은,마루 출판사,2007-2008,04810,NaN,https://image.aladin.co.kr/product/92/4/cover/...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,5126198.0,9788953278974,1,신곡주계 폴리포니카,사카키 이치로 지음 ;이형선 옮김,서울문화사,2007-2014,04830,NaN,https://image.aladin.co.kr/product/91/3/cover/...,신곡 연주를 듣고 힘을 발휘하는 정령과 그 정령에게 힘을 주는 신곡 악사의 이야기....,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,5126199.0,9788953279506,2,신곡주계 폴리포니카,사카키 이치로 지음 ;이형선 옮김,서울문화사,2007-2014,04830,NaN,https://image.aladin.co.kr/product/92/91/cover...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,5126200.0,9788953280250,3,신곡주계 폴리포니카,사카키 이치로 지음 ;이형선 옮김,서울문화사,2007-2014,04830,NaN,https://image.aladin.co.kr/product/103/51/cove...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,5126201.0,9788953284890,4,신곡주계 폴리포니카,사카키 이치로 지음 ;이형선 옮김,서울문화사,2007-2014,04830,NaN,https://image.aladin.co.kr/product/171/6/cover...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7597078,NaN,9791189850142,NaN,임복근 동화선집(지역작가),저자: 임복근,안북스,NaN,03650,NaN,NaN,NaN,6372305.0,NaN,임복근동화선집지역작가,저자임복근,NaN,Y,Y,NaN
7597082,NaN,9798997766963,NaN,Faith-Praxis 실천 신앙,마이클 장,NaN,NaN,13230,NaN,NaN,NaN,6372309.0,NaN,faithpraxis실천신앙,마이클장,NaN,Y,Y,NaN
7597097,NaN,9788986986273,NaN,"배 병우 Bae, Bien-U",사진: 배병우,가나아트센터,NaN,03600,NaN,NaN,NaN,6372325.0,NaN,"배병우bae,bienu",사진배병우,NaN,Y,Y,NaN
7597102,NaN,9788993518924,NaN,국립중앙박물관 상설전시,국립중앙박물관 [편],국립중앙박물관,NaN,03600,NaN,NaN,NaN,6372330.0,NaN,국립중앙박물관상설전시,국립중앙박물관편,NaN,Y,Y,NaN
7597114,NaN,9788993518931,NaN,아시아를 칠하다,국립중앙박물관 [편],국립중앙박물관,NaN,03630,NaN,NaN,NaN,6372342.0,NaN,아시아를칠하다,국립중앙박물관편,NaN,Y,Y,NaN

In [12]:
df.isnull().sum()

?master_seq       2385907
isbn13                539
vol               3027134
title                1227
author              20682
publisher          260106
pub_date          2375031
add_code                0
price             1124417
img_url           1376769
description       1714259
master_seq        1684826
kdc_class_no      1825981
title_replace     2054606
author_replace    2932089
pub_date_2        2404161
is_coll_aladin    1707228
is_coll_naver     1707228
isbn_origin       2251057
dtype: int64

In [13]:
df.drop_duplicates(['title'])
df

,?master_seq,isbn13,vol,title,author,publisher,pub_date,add_code,price,img_url,description,master_seq,kdc_class_no,title_replace,author_replace,pub_date_2,is_coll_aladin,is_coll_naver,isbn_origin
23,5126197.0,9788958945116,1,폭마전기 :정재은 新무협 장편소설,정재은,마루 출판사,2007-2008,04810,NaN,https://image.aladin.co.kr/product/92/4/cover/...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,5126198.0,9788953278974,1,신곡주계 폴리포니카,사카키 이치로 지음 ;이형선 옮김,서울문화사,2007-2014,04830,NaN,https://image.aladin.co.kr/product/91/3/cover/...,신곡 연주를 듣고 힘을 발휘하는 정령과 그 정령에게 힘을 주는 신곡 악사의 이야기....,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,5126199.0,9788953279506,2,신곡주계 폴리포니카,사카키 이치로 지음 ;이형선 옮김,서울문화사,2007-2014,04830,NaN,https://image.aladin.co.kr/product/92/91/cover...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,5126200.0,9788953280250,3,신곡주계 폴리포니카,사카키 이치로 지음 ;이형선 옮김,서울문화사,2007-2014,04830,NaN,https://image.aladin.co.kr/product/103/51/cove...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,5126201.0,9788953284890,4,신곡주계 폴리포니카,사카키 이치로 지음 ;이형선 옮김,서울문화사,2007-2014,04830,NaN,https://image.aladin.co.kr/product/171/6/cover...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7597078,NaN,9791189850142,NaN,임복근 동화선집(지역작가),저자: 임복근,안북스,NaN,03650,NaN,NaN,NaN,6372305.0,NaN,임복근동화선집지역작가,저자임복근,NaN,Y,Y,NaN
7597082,NaN,9798997766963,NaN,Faith-Praxis 실천 신앙,마이클 장,NaN,NaN,13230,NaN,NaN,NaN,6372309.0,NaN,faithpraxis실천신앙,마이클장,NaN,Y,Y,NaN
7597097,NaN,9788986986273,NaN,"배 병우 Bae, Bien-U",사진: 배병우,가나아트센터,NaN,03600,NaN,NaN,NaN,6372325.0,NaN,"배병우bae,bienu",사진배병우,NaN,Y,Y,NaN
7597102,NaN,9788993518924,NaN,국립중앙박물관 상설전시,국립중앙박물관 [편],국립중앙박물관,NaN,03600,NaN,NaN,NaN,6372330.0,NaN,국립중앙박물관상설전시,국립중앙박물관편,NaN,Y,Y,NaN
7597114,NaN,9788993518931,NaN,아시아를 칠하다,국립중앙박물관 [편],국립중앙박물관,NaN,03630,NaN,NaN,NaN,6372342.0,NaN,아시아를칠하다,국립중앙박물관편,NaN,Y,Y,NaN

In [14]:
df = df[df['kdc_class_no'].notna()]
df

,?master_seq,isbn13,vol,title,author,publisher,pub_date,add_code,price,img_url,description,master_seq,kdc_class_no,title_replace,author_replace,pub_date_2,is_coll_aladin,is_coll_naver,isbn_origin
3178515,NaN,9788982412677,NaN,(Power up)액세스 프로그래밍,박운재...[등]저,이한출판사,NaN,93000.0,16000.0,NaN,NaN,116161.0,5.756,powerup액세스프로그래밍,NaN,NaN,Y,Y,8982412670
3178516,NaN,9788995192740,NaN,(2001-2002년)일본의 구조개혁과 증권시장,홍인기 지음,두일넷,NaN,93320.0,26000.0,http://image.aladin.co.kr/product/30/12/cover/...,이 책은 세계 2위의 경제대국이지만 구조개혁 지연으로 장기 불황에 신음하고 있는 일...,116162.0,327.85,20012002년일본의구조개혁과증권시장,NaN,2001-10-16,Y,Y,8995192747
3178517,NaN,9788982412615,NaN,IBM 통합(Intergrated) 시스템,류성렬;한문희 공저,이한출판사,NaN,93000.0,14000.0,http://image.aladin.co.kr/product/28/26/cover/...,현장 실무자를 위한 IBM 서버 안내서. IBM AS/400D을 기능에 초점을 맞추...,116163.0,4.145,ibm통합intergrated시스템,NaN,2001-05-30,Y,Y,8982412611
3178518,NaN,9788975486456,NaN,(L=MS²학문의 기원)學習學,韓駿相 著,학지사,NaN,93370.0,16000.0,http://image.aladin.co.kr/product/30/12/cover/...,학습학 사상과 원형을 탐구한 책. 배우고 익히는 인간의 아름다움과 동시에 실천이라는...,116165.0,370.0,lms²학문의기원學習學,NaN,2001-09-25,Y,Y,8975486451
3178519,NaN,9788982412738,NaN,인터넷에 점포차리기,지란지교소프트 저,이한출판사,NaN,93000.0,19000.0,http://image.aladin.co.kr/product/30/25/cover/...,"이제 전자상거래의 중심에 선다, 책 한권으로 인터넷 쇼핑몰 사업가로 화려한 변신! ...",116166.0,326.165,인터넷에점포차리기,NaN,2001-08-30,Y,Y,8982412735
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7589490,NaN,9788972581222,12:,특급추리뤼팽시리즈,모리스 르블랑 지음;장숙자 옮김,유진,NaN,74860,5000.0,NaN,NaN,2813807.0,863.0,특급추리뤼팽시리즈,모리스르블랑지음장숙자옮김,1995-02-01,Y,Y,9788972581222
7589491,NaN,9788983311634,1-1 - 1-24/,두리의 우주선 여행,글: 오현경 ;그림: 정효섭,비엔존,NaN,74370,NaN,NaN,NaN,141305.0,410.0,두리의우주선여행,글오현경그림정효섭,NaN,Y,Y,8983311630 (세트)
7589492,NaN,9788983311511,114,두리의 우주선 여행,글: 오현경 ;그림: 정효섭,비엔존,NaN,74370,8800.0,NaN,NaN,335993.0,410.0,두리의우주선여행,글오현경그림정효섭,NaN,Y,Y,8983311517
7589504,NaN,9788971962305,1,산수보다 쉬운 수학,"지은이: 강성오,그린이: 박향미",사계절출판사,NaN,77410,4000.0,http://image.aladin.co.kr/product/7/9/cover/89...,원리와 개념을 정확히 이해하고 어린이들의 사고과정상의 연관성과 내용상의 유기적 관련...,2446221.0,410.0,산수보다쉬운수학,"지은이강성오,그린이박향미",1994-07-01,Y,Y,8971962305
7589505,NaN,9788971962312,2,산수보다 쉬운 수학,"지은이: 강성오,그린이: 박향미",사계절출판사,NaN,77410,4000.0,https://bookthumb-phinf.pstatic.net/cover/000/...,NaN,2556992.0,410.0,산수보다쉬운수학,"지은이강성오,그린이박향미",1994-07-01,Y,Y,8971962313:

In [ ]:
isbn13 
title 
author
publisher       
add_code     
img_url
kdc_class_no      
title_replace     
author_replace

In [18]:
df.isna().sum()

?master_seq       2242985
isbn13                  0
vol               1616826
title                   0
author               7743
publisher          126819
pub_date          2229176
add_code                0
price              603041
img_url            749084
description        928353
master_seq              0
kdc_class_no            0
title_replace      366221
author_replace    1177906
pub_date_2         686803
is_coll_aladin      22401
is_coll_naver       22401
isbn_origin        492949
dtype: int64

In [24]:
book_list = df[['isbn13','title','author','publisher','add_code','img_url','kdc_class_no','title_replace','author_replace']]

In [25]:
book_list.isna().sum()

isbn13                  0
title                   0
author               7743
publisher          126819
add_code                0
img_url            749084
kdc_class_no            0
title_replace      366221
author_replace    1177906
dtype: int64

In [26]:
book_list['author'] = book_list['author'].fillna('저자 미상')

In [27]:
book_list.isna().sum()

isbn13                  0
title                   0
author                  0
publisher          126819
add_code                0
img_url            749084
kdc_class_no            0
title_replace      366221
author_replace    1177906
dtype: int64

In [28]:
book_list.to_csv('../data/book_list_final.csv')

In [29]:
book_list.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2242985 entries, 3178515 to 7589505
Data columns (total 9 columns):
 #   Column          Dtype
---  ------          -----
 0   isbn13          object
 1   title           object
 2   author          object
 3   publisher       object
 4   add_code        object
 5   img_url         object
 6   kdc_class_no    object
 7   title_replace   object
 8   author_replace  object
dtypes: object(9)
memory usage: 171.1+ MB

In [8]:
df = pd.read_csv('../data/book_list/book_list_final.csv')
df.info()
display(df.head())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2242985 entries, 0 to 2242984
Data columns (total 10 columns):
 #   Column          Dtype
---  ------          -----
 0   Unnamed: 0      int64
 1   isbn13          object
 2   title           object
 3   author          object
 4   publisher       object
 5   add_code        object
 6   img_url         object
 7   kdc_class_no    object
 8   title_replace   object
 9   author_replace  object
dtypes: int64(1), object(9)
memory usage: 171.1+ MB

,Unnamed: 0,isbn13,title,author,publisher,add_code,img_url,kdc_class_no,title_replace,author_replace
0,3178515,9788982412677,(Power up)액세스 프로그래밍,박운재...[등]저,이한출판사,93000.0,NaN,5.756,powerup액세스프로그래밍,NaN
1,3178516,9788995192740,(2001-2002년)일본의 구조개혁과 증권시장,홍인기 지음,두일넷,93320.0,http://image.aladin.co.kr/product/30/12/cover/...,327.85,20012002년일본의구조개혁과증권시장,NaN
2,3178517,9788982412615,IBM 통합(Intergrated) 시스템,류성렬;한문희 공저,이한출판사,93000.0,http://image.aladin.co.kr/product/28/26/cover/...,4.145,ibm통합intergrated시스템,NaN
3,3178518,9788975486456,(L=MS²학문의 기원)學習學,韓駿相 著,학지사,93370.0,http://image.aladin.co.kr/product/30/12/cover/...,370.0,lms²학문의기원學習學,NaN
4,3178519,9788982412738,인터넷에 점포차리기,지란지교소프트 저,이한출판사,93000.0,http://image.aladin.co.kr/product/30/25/cover/...,326.165,인터넷에점포차리기,NaN

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2242985 entries, 0 to 2242984
Data columns (total 10 columns):
 #   Column          Dtype
---  ------          -----
 0   Unnamed: 0      int64
 1   isbn13          object
 2   title           object
 3   author          object
 4   publisher       object
 5   add_code        object
 6   img_url         object
 7   kdc_class_no    object
 8   title_replace   object
 9   author_replace  object
dtypes: int64(1), object(9)
memory usage: 171.1+ MB

In [10]:
df = df.drop(['title_replace','author_replace','img_url'], axis=1)

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2242985 entries, 0 to 2242984
Data columns (total 7 columns):
 #   Column        Dtype
---  ------        -----
 0   Unnamed: 0    int64
 1   isbn13        object
 2   title         object
 3   author        object
 4   publisher     object
 5   add_code      object
 6   kdc_class_no  object
dtypes: int64(1), object(6)
memory usage: 119.8+ MB

In [12]:
df.isnull().sum()

Unnamed: 0           0
isbn13               0
title                0
author               0
publisher       126819
add_code             0
kdc_class_no         0
dtype: int64

In [ ]:
df['publisher'].dropna()

In [ ]:
df.isnull().sum()

In [13]:
df.to_csv('../data/book_list_final.csv')

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('../data/book_list_final.csv')

C:\Users\yibob\AppData\Local\Temp\ipykernel_18784\3589907901.py:1: DtypeWarning: Columns (2,6,7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('../data/book_list_final.csv')

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2242985 entries, 0 to 2242984
Data columns (total 8 columns):
 #   Column        Dtype
---  ------        -----
 0   Unnamed: 0.1  int64
 1   Unnamed: 0    int64
 2   isbn13        object
 3   title         object
 4   author        object
 5   publisher     object
 6   add_code      object
 7   kdc_class_no  object
dtypes: int64(2), object(6)
memory usage: 136.9+ MB